gcc -o +x/main.+x main.c
gcc -o +x/game.+x game.c
gcc -o +x/file_submenu.+x file_submenu.c
gcc -o +x/settings_submenu.+x settings_submenu.c
gcc -o +x/wsr_clock.+x wsr_clock.c
gcc -o +x/db_search.+x db_search.c
gcc -o +x/setup_corporations.+x setup_corporations.c
gcc -o +x/setup_corporations_stage2.+x setup_corporations_stage2.c
gcc -o +x/setup_governments.+x setup_governments.c
gcc -o +x/ai_module.+x ai_module.c
gcc -o +x/game_setup.+x game_setup.c
gcc -o +x/select_entity.+x select_entity.c
gcc -o +x/financing.+x financing.c
